repos:
- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.11

# - repo: local
#   hooks:
#     - id: ruff
#       name: Run ruff
#       entry: ruff --fix
#       language: system
#       stages: [commit]